K8s Deployment Improvements
defenseunicorns/leapfrogai-ui pull request #107
Opened 2024-02-03 23:14 UTC by YrrepNoj

This PR introduces Helm charts to manage our k8s deployment. This moves us away from using raw manifests and moves us a lot closer to the standards for deployments that are seen across the company.

2024-02-05 22:12 UTC, justinthelaw requested changes

2024-02-05 22:12 UTC, justinthelaw commented on chart/Chart.yaml
> +appVersion: "1.16.0"
This should match the current version, 0.2.0

2024-02-05 22:12 UTC, justinthelaw commented on chart/Chart.yaml
> +version: 0.4.4
Assuming we are seeing this as a new-start, this should be 0.1.0.

2024-02-05 22:12 UTC, justinthelaw commented on manifests/istio.yaml
> -apiVersion: networking.istio.io/v1alpha3
This file's redirect and rewrite specs are still required for deployment to a standalone k3d cluster (non-UDS). I assume this is being removed because UDS does this differently?

2024-02-07 06:36 UTC, YrrepNoj commented on manifests/istio.yaml
> -apiVersion: networking.istio.io/v1alpha3
This is handled automagically on UDS (through the power of Pepr)

2024-02-07 06:39 UTC, YrrepNoj commented on chart/Chart.yaml
> +version: 0.4.4
Updated

2024-02-07 06:39 UTC, YrrepNoj commented on chart/Chart.yaml
> +appVersion: "1.16.0"
Updated

2024-02-07 13:45 UTC, justinthelaw submitted a review, later dismissed
As long as the UDS deployment is good by our next install, I am good. Otherwise @CollectiveUnicorn and I will re-instate the Istio configuration we had.

2024-02-23 17:34 UTC, justinthelaw approved these changes

2024-02-23 17:50 UTC, merged